//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2012
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankingWebApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Seed", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Seed : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fone3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private System.DateTime BirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniversityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseField;
        
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchoolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreparatoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        private System.DateTime SubscriptionField;
        
        private bool MentorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Facebook {
            get {
                return this.FacebookField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookField, value) != true)) {
                    this.FacebookField = value;
                    this.RaisePropertyChanged("Facebook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Fone {
            get {
                return this.FoneField;
            }
            set {
                if ((object.ReferenceEquals(this.FoneField, value) != true)) {
                    this.FoneField = value;
                    this.RaisePropertyChanged("Fone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Fone2 {
            get {
                return this.Fone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Fone2Field, value) != true)) {
                    this.Fone2Field = value;
                    this.RaisePropertyChanged("Fone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Fone3 {
            get {
                return this.Fone3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Fone3Field, value) != true)) {
                    this.Fone3Field = value;
                    this.RaisePropertyChanged("Fone3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime Birth {
            get {
                return this.BirthField;
            }
            set {
                if ((this.BirthField.Equals(value) != true)) {
                    this.BirthField = value;
                    this.RaisePropertyChanged("Birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string University {
            get {
                return this.UniversityField;
            }
            set {
                if ((object.ReferenceEquals(this.UniversityField, value) != true)) {
                    this.UniversityField = value;
                    this.RaisePropertyChanged("University");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Course {
            get {
                return this.CourseField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseField, value) != true)) {
                    this.CourseField = value;
                    this.RaisePropertyChanged("Course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string School {
            get {
                return this.SchoolField;
            }
            set {
                if ((object.ReferenceEquals(this.SchoolField, value) != true)) {
                    this.SchoolField = value;
                    this.RaisePropertyChanged("School");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Preparatory {
            get {
                return this.PreparatoryField;
            }
            set {
                if ((object.ReferenceEquals(this.PreparatoryField, value) != true)) {
                    this.PreparatoryField = value;
                    this.RaisePropertyChanged("Preparatory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.DateTime Subscription {
            get {
                return this.SubscriptionField;
            }
            set {
                if ((this.SubscriptionField.Equals(value) != true)) {
                    this.SubscriptionField = value;
                    this.RaisePropertyChanged("Subscription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public bool Mentor {
            get {
                return this.MentorField;
            }
            set {
                if ((this.MentorField.Equals(value) != true)) {
                    this.MentorField = value;
                    this.RaisePropertyChanged("Mentor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name GetAppNameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAppName", ReplyAction="*")]
        RankingWebApp.ServiceReference1.GetAppNameResponse GetAppName(RankingWebApp.ServiceReference1.GetAppNameRequest request);
        
        // CODEGEN: Generating message contract since element name items from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditMultiParamUser", ReplyAction="*")]
        RankingWebApp.ServiceReference1.EditMultiParamUserResponse EditMultiParamUser(RankingWebApp.ServiceReference1.EditMultiParamUserRequest request);
        
        // CODEGEN: Generating message contract since element name items from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateMultiParamUser", ReplyAction="*")]
        RankingWebApp.ServiceReference1.CreateMultiParamUserResponse CreateMultiParamUser(RankingWebApp.ServiceReference1.CreateMultiParamUserRequest request);
        
        // CODEGEN: Generating message contract since element name field from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSeed", ReplyAction="*")]
        RankingWebApp.ServiceReference1.GetSeedResponse GetSeed(RankingWebApp.ServiceReference1.GetSeedRequest request);
        
        // CODEGEN: Generating message contract since element name list from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItem", ReplyAction="*")]
        RankingWebApp.ServiceReference1.GetItemResponse GetItem(RankingWebApp.ServiceReference1.GetItemRequest request);
        
        // CODEGEN: Generating message contract since element name field from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSeedSearch", ReplyAction="*")]
        RankingWebApp.ServiceReference1.GetSeedSearchResponse GetSeedSearch(RankingWebApp.ServiceReference1.GetSeedSearchRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        RankingWebApp.ServiceReference1.GetListResponse GetList(RankingWebApp.ServiceReference1.GetListRequest request);
        
        // CODEGEN: Generating message contract since element name GetSeedListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSeedList", ReplyAction="*")]
        RankingWebApp.ServiceReference1.GetSeedListResponse GetSeedList(RankingWebApp.ServiceReference1.GetSeedListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConnectMentorSeed", ReplyAction="*")]
        void ConnectMentorSeed(int mentorID, int seedID);
        
        // CODEGEN: Generating message contract since element name GetMentorbySeedResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMentorbySeed", ReplyAction="*")]
        RankingWebApp.ServiceReference1.GetMentorbySeedResponse GetMentorbySeed(RankingWebApp.ServiceReference1.GetMentorbySeedRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSeedID", ReplyAction="*")]
        RankingWebApp.ServiceReference1.GetSeedIDResponse GetSeedID(RankingWebApp.ServiceReference1.GetSeedIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAppNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAppName", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetAppNameRequestBody Body;
        
        public GetAppNameRequest() {
        }
        
        public GetAppNameRequest(RankingWebApp.ServiceReference1.GetAppNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAppNameRequestBody {
        
        public GetAppNameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAppNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAppNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetAppNameResponseBody Body;
        
        public GetAppNameResponse() {
        }
        
        public GetAppNameResponse(RankingWebApp.ServiceReference1.GetAppNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAppNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAppNameResult;
        
        public GetAppNameResponseBody() {
        }
        
        public GetAppNameResponseBody(string GetAppNameResult) {
            this.GetAppNameResult = GetAppNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditMultiParamUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditMultiParamUser", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.EditMultiParamUserRequestBody Body;
        
        public EditMultiParamUserRequest() {
        }
        
        public EditMultiParamUserRequest(RankingWebApp.ServiceReference1.EditMultiParamUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditMultiParamUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public RankingWebApp.ServiceReference1.ArrayOfString items;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public RankingWebApp.ServiceReference1.ArrayOfString values;
        
        public EditMultiParamUserRequestBody() {
        }
        
        public EditMultiParamUserRequestBody(int id, RankingWebApp.ServiceReference1.ArrayOfString items, RankingWebApp.ServiceReference1.ArrayOfString values) {
            this.id = id;
            this.items = items;
            this.values = values;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditMultiParamUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditMultiParamUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.EditMultiParamUserResponseBody Body;
        
        public EditMultiParamUserResponse() {
        }
        
        public EditMultiParamUserResponse(RankingWebApp.ServiceReference1.EditMultiParamUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditMultiParamUserResponseBody {
        
        public EditMultiParamUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMultiParamUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateMultiParamUser", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateMultiParamUserRequestBody Body;
        
        public CreateMultiParamUserRequest() {
        }
        
        public CreateMultiParamUserRequest(RankingWebApp.ServiceReference1.CreateMultiParamUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateMultiParamUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RankingWebApp.ServiceReference1.ArrayOfString items;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public RankingWebApp.ServiceReference1.ArrayOfString values;
        
        public CreateMultiParamUserRequestBody() {
        }
        
        public CreateMultiParamUserRequestBody(RankingWebApp.ServiceReference1.ArrayOfString items, RankingWebApp.ServiceReference1.ArrayOfString values) {
            this.items = items;
            this.values = values;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMultiParamUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateMultiParamUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateMultiParamUserResponseBody Body;
        
        public CreateMultiParamUserResponse() {
        }
        
        public CreateMultiParamUserResponse(RankingWebApp.ServiceReference1.CreateMultiParamUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateMultiParamUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateMultiParamUserResult;
        
        public CreateMultiParamUserResponseBody() {
        }
        
        public CreateMultiParamUserResponseBody(bool CreateMultiParamUserResult) {
            this.CreateMultiParamUserResult = CreateMultiParamUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSeedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeed", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetSeedRequestBody Body;
        
        public GetSeedRequest() {
        }
        
        public GetSeedRequest(RankingWebApp.ServiceReference1.GetSeedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSeedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string item;
        
        public GetSeedRequestBody() {
        }
        
        public GetSeedRequestBody(string field, string item) {
            this.field = field;
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSeedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeedResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetSeedResponseBody Body;
        
        public GetSeedResponse() {
        }
        
        public GetSeedResponse(RankingWebApp.ServiceReference1.GetSeedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSeedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RankingWebApp.ServiceReference1.Seed GetSeedResult;
        
        public GetSeedResponseBody() {
        }
        
        public GetSeedResponseBody(RankingWebApp.ServiceReference1.Seed GetSeedResult) {
            this.GetSeedResult = GetSeedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItem", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetItemRequestBody Body;
        
        public GetItemRequest() {
        }
        
        public GetItemRequest(RankingWebApp.ServiceReference1.GetItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string list;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string item;
        
        public GetItemRequestBody() {
        }
        
        public GetItemRequestBody(string list, string field, string item) {
            this.list = list;
            this.field = field;
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetItemResponseBody Body;
        
        public GetItemResponse() {
        }
        
        public GetItemResponse(RankingWebApp.ServiceReference1.GetItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetItemResult;
        
        public GetItemResponseBody() {
        }
        
        public GetItemResponseBody(string GetItemResult) {
            this.GetItemResult = GetItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSeedSearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeedSearch", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetSeedSearchRequestBody Body;
        
        public GetSeedSearchRequest() {
        }
        
        public GetSeedSearchRequest(RankingWebApp.ServiceReference1.GetSeedSearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSeedSearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string item;
        
        public GetSeedSearchRequestBody() {
        }
        
        public GetSeedSearchRequestBody(string field, string item) {
            this.field = field;
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSeedSearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeedSearchResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetSeedSearchResponseBody Body;
        
        public GetSeedSearchResponse() {
        }
        
        public GetSeedSearchResponse(RankingWebApp.ServiceReference1.GetSeedSearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSeedSearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RankingWebApp.ServiceReference1.Seed[] GetSeedSearchResult;
        
        public GetSeedSearchResponseBody() {
        }
        
        public GetSeedSearchResponseBody(RankingWebApp.ServiceReference1.Seed[] GetSeedSearchResult) {
            this.GetSeedSearchResult = GetSeedSearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetList", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetListRequestBody Body;
        
        public GetListRequest() {
        }
        
        public GetListRequest(RankingWebApp.ServiceReference1.GetListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string item;
        
        public GetListRequestBody() {
        }
        
        public GetListRequestBody(string item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetListResponseBody Body;
        
        public GetListResponse() {
        }
        
        public GetListResponse(RankingWebApp.ServiceReference1.GetListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RankingWebApp.ServiceReference1.ArrayOfString GetListResult;
        
        public GetListResponseBody() {
        }
        
        public GetListResponseBody(RankingWebApp.ServiceReference1.ArrayOfString GetListResult) {
            this.GetListResult = GetListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSeedListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeedList", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetSeedListRequestBody Body;
        
        public GetSeedListRequest() {
        }
        
        public GetSeedListRequest(RankingWebApp.ServiceReference1.GetSeedListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSeedListRequestBody {
        
        public GetSeedListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSeedListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeedListResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetSeedListResponseBody Body;
        
        public GetSeedListResponse() {
        }
        
        public GetSeedListResponse(RankingWebApp.ServiceReference1.GetSeedListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSeedListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RankingWebApp.ServiceReference1.Seed[] GetSeedListResult;
        
        public GetSeedListResponseBody() {
        }
        
        public GetSeedListResponseBody(RankingWebApp.ServiceReference1.Seed[] GetSeedListResult) {
            this.GetSeedListResult = GetSeedListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMentorbySeedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMentorbySeed", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetMentorbySeedRequestBody Body;
        
        public GetMentorbySeedRequest() {
        }
        
        public GetMentorbySeedRequest(RankingWebApp.ServiceReference1.GetMentorbySeedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMentorbySeedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SeedId;
        
        public GetMentorbySeedRequestBody() {
        }
        
        public GetMentorbySeedRequestBody(int SeedId) {
            this.SeedId = SeedId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMentorbySeedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMentorbySeedResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetMentorbySeedResponseBody Body;
        
        public GetMentorbySeedResponse() {
        }
        
        public GetMentorbySeedResponse(RankingWebApp.ServiceReference1.GetMentorbySeedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMentorbySeedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RankingWebApp.ServiceReference1.Seed GetMentorbySeedResult;
        
        public GetMentorbySeedResponseBody() {
        }
        
        public GetMentorbySeedResponseBody(RankingWebApp.ServiceReference1.Seed GetMentorbySeedResult) {
            this.GetMentorbySeedResult = GetMentorbySeedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSeedIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeedID", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetSeedIDRequestBody Body;
        
        public GetSeedIDRequest() {
        }
        
        public GetSeedIDRequest(RankingWebApp.ServiceReference1.GetSeedIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSeedIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        public GetSeedIDRequestBody() {
        }
        
        public GetSeedIDRequestBody(string Name) {
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSeedIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeedIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetSeedIDResponseBody Body;
        
        public GetSeedIDResponse() {
        }
        
        public GetSeedIDResponse(RankingWebApp.ServiceReference1.GetSeedIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSeedIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetSeedIDResult;
        
        public GetSeedIDResponseBody() {
        }
        
        public GetSeedIDResponseBody(int GetSeedIDResult) {
            this.GetSeedIDResult = GetSeedIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : RankingWebApp.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<RankingWebApp.ServiceReference1.Service1Soap>, RankingWebApp.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.GetAppNameResponse RankingWebApp.ServiceReference1.Service1Soap.GetAppName(RankingWebApp.ServiceReference1.GetAppNameRequest request) {
            return base.Channel.GetAppName(request);
        }
        
        public string GetAppName() {
            RankingWebApp.ServiceReference1.GetAppNameRequest inValue = new RankingWebApp.ServiceReference1.GetAppNameRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.GetAppNameRequestBody();
            RankingWebApp.ServiceReference1.GetAppNameResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).GetAppName(inValue);
            return retVal.Body.GetAppNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.EditMultiParamUserResponse RankingWebApp.ServiceReference1.Service1Soap.EditMultiParamUser(RankingWebApp.ServiceReference1.EditMultiParamUserRequest request) {
            return base.Channel.EditMultiParamUser(request);
        }
        
        public void EditMultiParamUser(int id, RankingWebApp.ServiceReference1.ArrayOfString items, RankingWebApp.ServiceReference1.ArrayOfString values) {
            RankingWebApp.ServiceReference1.EditMultiParamUserRequest inValue = new RankingWebApp.ServiceReference1.EditMultiParamUserRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.EditMultiParamUserRequestBody();
            inValue.Body.id = id;
            inValue.Body.items = items;
            inValue.Body.values = values;
            RankingWebApp.ServiceReference1.EditMultiParamUserResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).EditMultiParamUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.CreateMultiParamUserResponse RankingWebApp.ServiceReference1.Service1Soap.CreateMultiParamUser(RankingWebApp.ServiceReference1.CreateMultiParamUserRequest request) {
            return base.Channel.CreateMultiParamUser(request);
        }
        
        public bool CreateMultiParamUser(RankingWebApp.ServiceReference1.ArrayOfString items, RankingWebApp.ServiceReference1.ArrayOfString values) {
            RankingWebApp.ServiceReference1.CreateMultiParamUserRequest inValue = new RankingWebApp.ServiceReference1.CreateMultiParamUserRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.CreateMultiParamUserRequestBody();
            inValue.Body.items = items;
            inValue.Body.values = values;
            RankingWebApp.ServiceReference1.CreateMultiParamUserResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).CreateMultiParamUser(inValue);
            return retVal.Body.CreateMultiParamUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.GetSeedResponse RankingWebApp.ServiceReference1.Service1Soap.GetSeed(RankingWebApp.ServiceReference1.GetSeedRequest request) {
            return base.Channel.GetSeed(request);
        }
        
        public RankingWebApp.ServiceReference1.Seed GetSeed(string field, string item) {
            RankingWebApp.ServiceReference1.GetSeedRequest inValue = new RankingWebApp.ServiceReference1.GetSeedRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.GetSeedRequestBody();
            inValue.Body.field = field;
            inValue.Body.item = item;
            RankingWebApp.ServiceReference1.GetSeedResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).GetSeed(inValue);
            return retVal.Body.GetSeedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.GetItemResponse RankingWebApp.ServiceReference1.Service1Soap.GetItem(RankingWebApp.ServiceReference1.GetItemRequest request) {
            return base.Channel.GetItem(request);
        }
        
        public string GetItem(string list, string field, string item) {
            RankingWebApp.ServiceReference1.GetItemRequest inValue = new RankingWebApp.ServiceReference1.GetItemRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.GetItemRequestBody();
            inValue.Body.list = list;
            inValue.Body.field = field;
            inValue.Body.item = item;
            RankingWebApp.ServiceReference1.GetItemResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).GetItem(inValue);
            return retVal.Body.GetItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.GetSeedSearchResponse RankingWebApp.ServiceReference1.Service1Soap.GetSeedSearch(RankingWebApp.ServiceReference1.GetSeedSearchRequest request) {
            return base.Channel.GetSeedSearch(request);
        }
        
        public RankingWebApp.ServiceReference1.Seed[] GetSeedSearch(string field, string item) {
            RankingWebApp.ServiceReference1.GetSeedSearchRequest inValue = new RankingWebApp.ServiceReference1.GetSeedSearchRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.GetSeedSearchRequestBody();
            inValue.Body.field = field;
            inValue.Body.item = item;
            RankingWebApp.ServiceReference1.GetSeedSearchResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).GetSeedSearch(inValue);
            return retVal.Body.GetSeedSearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.GetListResponse RankingWebApp.ServiceReference1.Service1Soap.GetList(RankingWebApp.ServiceReference1.GetListRequest request) {
            return base.Channel.GetList(request);
        }
        
        public RankingWebApp.ServiceReference1.ArrayOfString GetList(string item) {
            RankingWebApp.ServiceReference1.GetListRequest inValue = new RankingWebApp.ServiceReference1.GetListRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.GetListRequestBody();
            inValue.Body.item = item;
            RankingWebApp.ServiceReference1.GetListResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).GetList(inValue);
            return retVal.Body.GetListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.GetSeedListResponse RankingWebApp.ServiceReference1.Service1Soap.GetSeedList(RankingWebApp.ServiceReference1.GetSeedListRequest request) {
            return base.Channel.GetSeedList(request);
        }
        
        public RankingWebApp.ServiceReference1.Seed[] GetSeedList() {
            RankingWebApp.ServiceReference1.GetSeedListRequest inValue = new RankingWebApp.ServiceReference1.GetSeedListRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.GetSeedListRequestBody();
            RankingWebApp.ServiceReference1.GetSeedListResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).GetSeedList(inValue);
            return retVal.Body.GetSeedListResult;
        }
        
        public void ConnectMentorSeed(int mentorID, int seedID) {
            base.Channel.ConnectMentorSeed(mentorID, seedID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.GetMentorbySeedResponse RankingWebApp.ServiceReference1.Service1Soap.GetMentorbySeed(RankingWebApp.ServiceReference1.GetMentorbySeedRequest request) {
            return base.Channel.GetMentorbySeed(request);
        }
        
        public RankingWebApp.ServiceReference1.Seed GetMentorbySeed(int SeedId) {
            RankingWebApp.ServiceReference1.GetMentorbySeedRequest inValue = new RankingWebApp.ServiceReference1.GetMentorbySeedRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.GetMentorbySeedRequestBody();
            inValue.Body.SeedId = SeedId;
            RankingWebApp.ServiceReference1.GetMentorbySeedResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).GetMentorbySeed(inValue);
            return retVal.Body.GetMentorbySeedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.GetSeedIDResponse RankingWebApp.ServiceReference1.Service1Soap.GetSeedID(RankingWebApp.ServiceReference1.GetSeedIDRequest request) {
            return base.Channel.GetSeedID(request);
        }
        
        public int GetSeedID(string Name) {
            RankingWebApp.ServiceReference1.GetSeedIDRequest inValue = new RankingWebApp.ServiceReference1.GetSeedIDRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.GetSeedIDRequestBody();
            inValue.Body.Name = Name;
            RankingWebApp.ServiceReference1.GetSeedIDResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).GetSeedID(inValue);
            return retVal.Body.GetSeedIDResult;
        }
    }
}
