//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2012
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankingWebApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Seed", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Seed : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fone3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private System.DateTime BirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vlausField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Facebook {
            get {
                return this.FacebookField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookField, value) != true)) {
                    this.FacebookField = value;
                    this.RaisePropertyChanged("Facebook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Fone {
            get {
                return this.FoneField;
            }
            set {
                if ((object.ReferenceEquals(this.FoneField, value) != true)) {
                    this.FoneField = value;
                    this.RaisePropertyChanged("Fone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Fone2 {
            get {
                return this.Fone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Fone2Field, value) != true)) {
                    this.Fone2Field = value;
                    this.RaisePropertyChanged("Fone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Fone3 {
            get {
                return this.Fone3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Fone3Field, value) != true)) {
                    this.Fone3Field = value;
                    this.RaisePropertyChanged("Fone3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime Birth {
            get {
                return this.BirthField;
            }
            set {
                if ((this.BirthField.Equals(value) != true)) {
                    this.BirthField = value;
                    this.RaisePropertyChanged("Birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string vlaus {
            get {
                return this.vlausField;
            }
            set {
                if ((object.ReferenceEquals(this.vlausField, value) != true)) {
                    this.vlausField = value;
                    this.RaisePropertyChanged("vlaus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUser", ReplyAction="*")]
        RankingWebApp.ServiceReference1.CreateUserResponse CreateUser(RankingWebApp.ServiceReference1.CreateUserRequest request);
        
        // CODEGEN: Generating message contract since element name items from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateMultiParamUser", ReplyAction="*")]
        RankingWebApp.ServiceReference1.CreateMultiParamUserResponse CreateMultiParamUser(RankingWebApp.ServiceReference1.CreateMultiParamUserRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateFaceBookUser", ReplyAction="*")]
        RankingWebApp.ServiceReference1.CreateFaceBookUserResponse CreateFaceBookUser(RankingWebApp.ServiceReference1.CreateFaceBookUserRequest request);
        
        // CODEGEN: Generating message contract since element name field from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSeed", ReplyAction="*")]
        RankingWebApp.ServiceReference1.GetSeedResponse GetSeed(RankingWebApp.ServiceReference1.GetSeedRequest request);
        
        // CODEGEN: Generating message contract since element name list from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItem", ReplyAction="*")]
        RankingWebApp.ServiceReference1.GetItemResponse GetItem(RankingWebApp.ServiceReference1.GetItemRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        RankingWebApp.ServiceReference1.GetListResponse GetList(RankingWebApp.ServiceReference1.GetListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUser", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateUserRequestBody Body;
        
        public CreateUserRequest() {
        }
        
        public CreateUserRequest(RankingWebApp.ServiceReference1.CreateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FileName;
        
        public CreateUserRequestBody() {
        }
        
        public CreateUserRequestBody(string Name, string FileName) {
            this.Name = Name;
            this.FileName = FileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateUserResponseBody Body;
        
        public CreateUserResponse() {
        }
        
        public CreateUserResponse(RankingWebApp.ServiceReference1.CreateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateUserResult;
        
        public CreateUserResponseBody() {
        }
        
        public CreateUserResponseBody(bool CreateUserResult) {
            this.CreateUserResult = CreateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMultiParamUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateMultiParamUser", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateMultiParamUserRequestBody Body;
        
        public CreateMultiParamUserRequest() {
        }
        
        public CreateMultiParamUserRequest(RankingWebApp.ServiceReference1.CreateMultiParamUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateMultiParamUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RankingWebApp.ServiceReference1.ArrayOfString items;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public RankingWebApp.ServiceReference1.ArrayOfString values;
        
        public CreateMultiParamUserRequestBody() {
        }
        
        public CreateMultiParamUserRequestBody(RankingWebApp.ServiceReference1.ArrayOfString items, RankingWebApp.ServiceReference1.ArrayOfString values) {
            this.items = items;
            this.values = values;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMultiParamUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateMultiParamUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateMultiParamUserResponseBody Body;
        
        public CreateMultiParamUserResponse() {
        }
        
        public CreateMultiParamUserResponse(RankingWebApp.ServiceReference1.CreateMultiParamUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateMultiParamUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateMultiParamUserResult;
        
        public CreateMultiParamUserResponseBody() {
        }
        
        public CreateMultiParamUserResponseBody(bool CreateMultiParamUserResult) {
            this.CreateMultiParamUserResult = CreateMultiParamUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFaceBookUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateFaceBookUser", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateFaceBookUserRequestBody Body;
        
        public CreateFaceBookUserRequest() {
        }
        
        public CreateFaceBookUserRequest(RankingWebApp.ServiceReference1.CreateFaceBookUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateFaceBookUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FaceBook;
        
        public CreateFaceBookUserRequestBody() {
        }
        
        public CreateFaceBookUserRequestBody(string Name, string FileName, string FaceBook) {
            this.Name = Name;
            this.FileName = FileName;
            this.FaceBook = FaceBook;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFaceBookUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateFaceBookUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateFaceBookUserResponseBody Body;
        
        public CreateFaceBookUserResponse() {
        }
        
        public CreateFaceBookUserResponse(RankingWebApp.ServiceReference1.CreateFaceBookUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateFaceBookUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateFaceBookUserResult;
        
        public CreateFaceBookUserResponseBody() {
        }
        
        public CreateFaceBookUserResponseBody(bool CreateFaceBookUserResult) {
            this.CreateFaceBookUserResult = CreateFaceBookUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSeedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeed", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetSeedRequestBody Body;
        
        public GetSeedRequest() {
        }
        
        public GetSeedRequest(RankingWebApp.ServiceReference1.GetSeedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSeedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string item;
        
        public GetSeedRequestBody() {
        }
        
        public GetSeedRequestBody(string field, string item) {
            this.field = field;
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSeedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeedResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetSeedResponseBody Body;
        
        public GetSeedResponse() {
        }
        
        public GetSeedResponse(RankingWebApp.ServiceReference1.GetSeedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSeedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RankingWebApp.ServiceReference1.Seed GetSeedResult;
        
        public GetSeedResponseBody() {
        }
        
        public GetSeedResponseBody(RankingWebApp.ServiceReference1.Seed GetSeedResult) {
            this.GetSeedResult = GetSeedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItem", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetItemRequestBody Body;
        
        public GetItemRequest() {
        }
        
        public GetItemRequest(RankingWebApp.ServiceReference1.GetItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string list;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string item;
        
        public GetItemRequestBody() {
        }
        
        public GetItemRequestBody(string list, string field, string item) {
            this.list = list;
            this.field = field;
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetItemResponseBody Body;
        
        public GetItemResponse() {
        }
        
        public GetItemResponse(RankingWebApp.ServiceReference1.GetItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetItemResult;
        
        public GetItemResponseBody() {
        }
        
        public GetItemResponseBody(string GetItemResult) {
            this.GetItemResult = GetItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetList", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetListRequestBody Body;
        
        public GetListRequest() {
        }
        
        public GetListRequest(RankingWebApp.ServiceReference1.GetListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string item;
        
        public GetListRequestBody() {
        }
        
        public GetListRequestBody(string item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetListResponseBody Body;
        
        public GetListResponse() {
        }
        
        public GetListResponse(RankingWebApp.ServiceReference1.GetListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RankingWebApp.ServiceReference1.ArrayOfString GetListResult;
        
        public GetListResponseBody() {
        }
        
        public GetListResponseBody(RankingWebApp.ServiceReference1.ArrayOfString GetListResult) {
            this.GetListResult = GetListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : RankingWebApp.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<RankingWebApp.ServiceReference1.Service1Soap>, RankingWebApp.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.CreateUserResponse RankingWebApp.ServiceReference1.Service1Soap.CreateUser(RankingWebApp.ServiceReference1.CreateUserRequest request) {
            return base.Channel.CreateUser(request);
        }
        
        public bool CreateUser(string Name, string FileName) {
            RankingWebApp.ServiceReference1.CreateUserRequest inValue = new RankingWebApp.ServiceReference1.CreateUserRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.CreateUserRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.FileName = FileName;
            RankingWebApp.ServiceReference1.CreateUserResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).CreateUser(inValue);
            return retVal.Body.CreateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.CreateMultiParamUserResponse RankingWebApp.ServiceReference1.Service1Soap.CreateMultiParamUser(RankingWebApp.ServiceReference1.CreateMultiParamUserRequest request) {
            return base.Channel.CreateMultiParamUser(request);
        }
        
        public bool CreateMultiParamUser(RankingWebApp.ServiceReference1.ArrayOfString items, RankingWebApp.ServiceReference1.ArrayOfString values) {
            RankingWebApp.ServiceReference1.CreateMultiParamUserRequest inValue = new RankingWebApp.ServiceReference1.CreateMultiParamUserRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.CreateMultiParamUserRequestBody();
            inValue.Body.items = items;
            inValue.Body.values = values;
            RankingWebApp.ServiceReference1.CreateMultiParamUserResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).CreateMultiParamUser(inValue);
            return retVal.Body.CreateMultiParamUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.CreateFaceBookUserResponse RankingWebApp.ServiceReference1.Service1Soap.CreateFaceBookUser(RankingWebApp.ServiceReference1.CreateFaceBookUserRequest request) {
            return base.Channel.CreateFaceBookUser(request);
        }
        
        public bool CreateFaceBookUser(string Name, string FileName, string FaceBook) {
            RankingWebApp.ServiceReference1.CreateFaceBookUserRequest inValue = new RankingWebApp.ServiceReference1.CreateFaceBookUserRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.CreateFaceBookUserRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.FileName = FileName;
            inValue.Body.FaceBook = FaceBook;
            RankingWebApp.ServiceReference1.CreateFaceBookUserResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).CreateFaceBookUser(inValue);
            return retVal.Body.CreateFaceBookUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.GetSeedResponse RankingWebApp.ServiceReference1.Service1Soap.GetSeed(RankingWebApp.ServiceReference1.GetSeedRequest request) {
            return base.Channel.GetSeed(request);
        }
        
        public RankingWebApp.ServiceReference1.Seed GetSeed(string field, string item) {
            RankingWebApp.ServiceReference1.GetSeedRequest inValue = new RankingWebApp.ServiceReference1.GetSeedRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.GetSeedRequestBody();
            inValue.Body.field = field;
            inValue.Body.item = item;
            RankingWebApp.ServiceReference1.GetSeedResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).GetSeed(inValue);
            return retVal.Body.GetSeedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.GetItemResponse RankingWebApp.ServiceReference1.Service1Soap.GetItem(RankingWebApp.ServiceReference1.GetItemRequest request) {
            return base.Channel.GetItem(request);
        }
        
        public string GetItem(string list, string field, string item) {
            RankingWebApp.ServiceReference1.GetItemRequest inValue = new RankingWebApp.ServiceReference1.GetItemRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.GetItemRequestBody();
            inValue.Body.list = list;
            inValue.Body.field = field;
            inValue.Body.item = item;
            RankingWebApp.ServiceReference1.GetItemResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).GetItem(inValue);
            return retVal.Body.GetItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.GetListResponse RankingWebApp.ServiceReference1.Service1Soap.GetList(RankingWebApp.ServiceReference1.GetListRequest request) {
            return base.Channel.GetList(request);
        }
        
        public RankingWebApp.ServiceReference1.ArrayOfString GetList(string item) {
            RankingWebApp.ServiceReference1.GetListRequest inValue = new RankingWebApp.ServiceReference1.GetListRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.GetListRequestBody();
            inValue.Body.item = item;
            RankingWebApp.ServiceReference1.GetListResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).GetList(inValue);
            return retVal.Body.GetListResult;
        }
    }
}
