//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankingWebApp.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateGame", ReplyAction="*")]
        RankingWebApp.ServiceReference.CreateGameResponse CreateGame(RankingWebApp.ServiceReference.CreateGameRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUser", ReplyAction="*")]
        RankingWebApp.ServiceReference.CreateUserResponse CreateUser(RankingWebApp.ServiceReference.CreateUserRequest request);
        
        // CODEGEN: Generating message contract since element name GameId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateRankingEntry", ReplyAction="*")]
        RankingWebApp.ServiceReference.CreateRankingEntryResponse CreateRankingEntry(RankingWebApp.ServiceReference.CreateRankingEntryRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        RankingWebApp.ServiceReference.GetListResponse GetList(RankingWebApp.ServiceReference.GetListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateGameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateGame", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference.CreateGameRequestBody Body;
        
        public CreateGameRequest() {
        }
        
        public CreateGameRequest(RankingWebApp.ServiceReference.CreateGameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateGameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Id;
        
        public CreateGameRequestBody() {
        }
        
        public CreateGameRequestBody(string Name, string Description, int Id) {
            this.Name = Name;
            this.Description = Description;
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateGameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateGameResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference.CreateGameResponseBody Body;
        
        public CreateGameResponse() {
        }
        
        public CreateGameResponse(RankingWebApp.ServiceReference.CreateGameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateGameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateGameResult;
        
        public CreateGameResponseBody() {
        }
        
        public CreateGameResponseBody(bool CreateGameResult) {
            this.CreateGameResult = CreateGameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUser", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference.CreateUserRequestBody Body;
        
        public CreateUserRequest() {
        }
        
        public CreateUserRequest(RankingWebApp.ServiceReference.CreateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FileName;
        
        public CreateUserRequestBody() {
        }
        
        public CreateUserRequestBody(string Name, string FileName) {
            this.Name = Name;
            this.FileName = FileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference.CreateUserResponseBody Body;
        
        public CreateUserResponse() {
        }
        
        public CreateUserResponse(RankingWebApp.ServiceReference.CreateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateUserResult;
        
        public CreateUserResponseBody() {
        }
        
        public CreateUserResponseBody(bool CreateUserResult) {
            this.CreateUserResult = CreateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRankingEntryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateRankingEntry", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference.CreateRankingEntryRequestBody Body;
        
        public CreateRankingEntryRequest() {
        }
        
        public CreateRankingEntryRequest(RankingWebApp.ServiceReference.CreateRankingEntryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateRankingEntryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GameId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Time;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Points;
        
        public CreateRankingEntryRequestBody() {
        }
        
        public CreateRankingEntryRequestBody(string GameId, string Time, string UserId, int Points) {
            this.GameId = GameId;
            this.Time = Time;
            this.UserId = UserId;
            this.Points = Points;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRankingEntryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateRankingEntryResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference.CreateRankingEntryResponseBody Body;
        
        public CreateRankingEntryResponse() {
        }
        
        public CreateRankingEntryResponse(RankingWebApp.ServiceReference.CreateRankingEntryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateRankingEntryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateRankingEntryResult;
        
        public CreateRankingEntryResponseBody() {
        }
        
        public CreateRankingEntryResponseBody(bool CreateRankingEntryResult) {
            this.CreateRankingEntryResult = CreateRankingEntryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetList", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference.GetListRequestBody Body;
        
        public GetListRequest() {
        }
        
        public GetListRequest(RankingWebApp.ServiceReference.GetListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string item;
        
        public GetListRequestBody() {
        }
        
        public GetListRequestBody(string item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference.GetListResponseBody Body;
        
        public GetListResponse() {
        }
        
        public GetListResponse(RankingWebApp.ServiceReference.GetListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RankingWebApp.ServiceReference.ArrayOfAnyType GetListResult;
        
        public GetListResponseBody() {
        }
        
        public GetListResponseBody(RankingWebApp.ServiceReference.ArrayOfAnyType GetListResult) {
            this.GetListResult = GetListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : RankingWebApp.ServiceReference.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<RankingWebApp.ServiceReference.Service1Soap>, RankingWebApp.ServiceReference.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference.CreateGameResponse RankingWebApp.ServiceReference.Service1Soap.CreateGame(RankingWebApp.ServiceReference.CreateGameRequest request) {
            return base.Channel.CreateGame(request);
        }
        
        public bool CreateGame(string Name, string Description, int Id) {
            RankingWebApp.ServiceReference.CreateGameRequest inValue = new RankingWebApp.ServiceReference.CreateGameRequest();
            inValue.Body = new RankingWebApp.ServiceReference.CreateGameRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Description = Description;
            inValue.Body.Id = Id;
            RankingWebApp.ServiceReference.CreateGameResponse retVal = ((RankingWebApp.ServiceReference.Service1Soap)(this)).CreateGame(inValue);
            return retVal.Body.CreateGameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference.CreateUserResponse RankingWebApp.ServiceReference.Service1Soap.CreateUser(RankingWebApp.ServiceReference.CreateUserRequest request) {
            return base.Channel.CreateUser(request);
        }
        
        public bool CreateUser(string Name, string FileName) {
            RankingWebApp.ServiceReference.CreateUserRequest inValue = new RankingWebApp.ServiceReference.CreateUserRequest();
            inValue.Body = new RankingWebApp.ServiceReference.CreateUserRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.FileName = FileName;
            RankingWebApp.ServiceReference.CreateUserResponse retVal = ((RankingWebApp.ServiceReference.Service1Soap)(this)).CreateUser(inValue);
            return retVal.Body.CreateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference.CreateRankingEntryResponse RankingWebApp.ServiceReference.Service1Soap.CreateRankingEntry(RankingWebApp.ServiceReference.CreateRankingEntryRequest request) {
            return base.Channel.CreateRankingEntry(request);
        }
        
        public bool CreateRankingEntry(string GameId, string Time, string UserId, int Points) {
            RankingWebApp.ServiceReference.CreateRankingEntryRequest inValue = new RankingWebApp.ServiceReference.CreateRankingEntryRequest();
            inValue.Body = new RankingWebApp.ServiceReference.CreateRankingEntryRequestBody();
            inValue.Body.GameId = GameId;
            inValue.Body.Time = Time;
            inValue.Body.UserId = UserId;
            inValue.Body.Points = Points;
            RankingWebApp.ServiceReference.CreateRankingEntryResponse retVal = ((RankingWebApp.ServiceReference.Service1Soap)(this)).CreateRankingEntry(inValue);
            return retVal.Body.CreateRankingEntryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference.GetListResponse RankingWebApp.ServiceReference.Service1Soap.GetList(RankingWebApp.ServiceReference.GetListRequest request) {
            return base.Channel.GetList(request);
        }
        
        public RankingWebApp.ServiceReference.ArrayOfAnyType GetList(string item) {
            RankingWebApp.ServiceReference.GetListRequest inValue = new RankingWebApp.ServiceReference.GetListRequest();
            inValue.Body = new RankingWebApp.ServiceReference.GetListRequestBody();
            inValue.Body.item = item;
            RankingWebApp.ServiceReference.GetListResponse retVal = ((RankingWebApp.ServiceReference.Service1Soap)(this)).GetList(inValue);
            return retVal.Body.GetListResult;
        }
    }
}
