//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankingWebApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateGame", ReplyAction="*")]
        RankingWebApp.ServiceReference1.CreateGameResponse CreateGame(RankingWebApp.ServiceReference1.CreateGameRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUser", ReplyAction="*")]
        RankingWebApp.ServiceReference1.CreateUserResponse CreateUser(RankingWebApp.ServiceReference1.CreateUserRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateFaceBookUser", ReplyAction="*")]
        RankingWebApp.ServiceReference1.CreateFaceBookUserResponse CreateFaceBookUser(RankingWebApp.ServiceReference1.CreateFaceBookUserRequest request);
        
        // CODEGEN: Generating message contract since element name GameId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateRankingEntry", ReplyAction="*")]
        RankingWebApp.ServiceReference1.CreateRankingEntryResponse CreateRankingEntry(RankingWebApp.ServiceReference1.CreateRankingEntryRequest request);
        
        // CODEGEN: Generating message contract since element name list from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItem", ReplyAction="*")]
        RankingWebApp.ServiceReference1.GetItemResponse GetItem(RankingWebApp.ServiceReference1.GetItemRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        RankingWebApp.ServiceReference1.GetListResponse GetList(RankingWebApp.ServiceReference1.GetListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateGameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateGame", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateGameRequestBody Body;
        
        public CreateGameRequest() {
        }
        
        public CreateGameRequest(RankingWebApp.ServiceReference1.CreateGameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateGameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Id;
        
        public CreateGameRequestBody() {
        }
        
        public CreateGameRequestBody(string Name, string Description, int Id) {
            this.Name = Name;
            this.Description = Description;
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateGameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateGameResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateGameResponseBody Body;
        
        public CreateGameResponse() {
        }
        
        public CreateGameResponse(RankingWebApp.ServiceReference1.CreateGameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateGameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateGameResult;
        
        public CreateGameResponseBody() {
        }
        
        public CreateGameResponseBody(bool CreateGameResult) {
            this.CreateGameResult = CreateGameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUser", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateUserRequestBody Body;
        
        public CreateUserRequest() {
        }
        
        public CreateUserRequest(RankingWebApp.ServiceReference1.CreateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FileName;
        
        public CreateUserRequestBody() {
        }
        
        public CreateUserRequestBody(string Name, string FileName) {
            this.Name = Name;
            this.FileName = FileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateUserResponseBody Body;
        
        public CreateUserResponse() {
        }
        
        public CreateUserResponse(RankingWebApp.ServiceReference1.CreateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateUserResult;
        
        public CreateUserResponseBody() {
        }
        
        public CreateUserResponseBody(bool CreateUserResult) {
            this.CreateUserResult = CreateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFaceBookUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateFaceBookUser", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateFaceBookUserRequestBody Body;
        
        public CreateFaceBookUserRequest() {
        }
        
        public CreateFaceBookUserRequest(RankingWebApp.ServiceReference1.CreateFaceBookUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateFaceBookUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FaceBook;
        
        public CreateFaceBookUserRequestBody() {
        }
        
        public CreateFaceBookUserRequestBody(string Name, string FileName, string FaceBook) {
            this.Name = Name;
            this.FileName = FileName;
            this.FaceBook = FaceBook;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFaceBookUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateFaceBookUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateFaceBookUserResponseBody Body;
        
        public CreateFaceBookUserResponse() {
        }
        
        public CreateFaceBookUserResponse(RankingWebApp.ServiceReference1.CreateFaceBookUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateFaceBookUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateFaceBookUserResult;
        
        public CreateFaceBookUserResponseBody() {
        }
        
        public CreateFaceBookUserResponseBody(bool CreateFaceBookUserResult) {
            this.CreateFaceBookUserResult = CreateFaceBookUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRankingEntryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateRankingEntry", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateRankingEntryRequestBody Body;
        
        public CreateRankingEntryRequest() {
        }
        
        public CreateRankingEntryRequest(RankingWebApp.ServiceReference1.CreateRankingEntryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateRankingEntryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GameId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Time;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Points;
        
        public CreateRankingEntryRequestBody() {
        }
        
        public CreateRankingEntryRequestBody(string GameId, string Time, string UserId, int Points) {
            this.GameId = GameId;
            this.Time = Time;
            this.UserId = UserId;
            this.Points = Points;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRankingEntryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateRankingEntryResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.CreateRankingEntryResponseBody Body;
        
        public CreateRankingEntryResponse() {
        }
        
        public CreateRankingEntryResponse(RankingWebApp.ServiceReference1.CreateRankingEntryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateRankingEntryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateRankingEntryResult;
        
        public CreateRankingEntryResponseBody() {
        }
        
        public CreateRankingEntryResponseBody(bool CreateRankingEntryResult) {
            this.CreateRankingEntryResult = CreateRankingEntryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItem", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetItemRequestBody Body;
        
        public GetItemRequest() {
        }
        
        public GetItemRequest(RankingWebApp.ServiceReference1.GetItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string list;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string item;
        
        public GetItemRequestBody() {
        }
        
        public GetItemRequestBody(string list, string field, string item) {
            this.list = list;
            this.field = field;
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetItemResponseBody Body;
        
        public GetItemResponse() {
        }
        
        public GetItemResponse(RankingWebApp.ServiceReference1.GetItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetItemResult;
        
        public GetItemResponseBody() {
        }
        
        public GetItemResponseBody(string GetItemResult) {
            this.GetItemResult = GetItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetList", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetListRequestBody Body;
        
        public GetListRequest() {
        }
        
        public GetListRequest(RankingWebApp.ServiceReference1.GetListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string item;
        
        public GetListRequestBody() {
        }
        
        public GetListRequestBody(string item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListResponse", Namespace="http://tempuri.org/", Order=0)]
        public RankingWebApp.ServiceReference1.GetListResponseBody Body;
        
        public GetListResponse() {
        }
        
        public GetListResponse(RankingWebApp.ServiceReference1.GetListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RankingWebApp.ServiceReference1.ArrayOfString GetListResult;
        
        public GetListResponseBody() {
        }
        
        public GetListResponseBody(RankingWebApp.ServiceReference1.ArrayOfString GetListResult) {
            this.GetListResult = GetListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : RankingWebApp.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<RankingWebApp.ServiceReference1.Service1Soap>, RankingWebApp.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.CreateGameResponse RankingWebApp.ServiceReference1.Service1Soap.CreateGame(RankingWebApp.ServiceReference1.CreateGameRequest request) {
            return base.Channel.CreateGame(request);
        }
        
        public bool CreateGame(string Name, string Description, int Id) {
            RankingWebApp.ServiceReference1.CreateGameRequest inValue = new RankingWebApp.ServiceReference1.CreateGameRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.CreateGameRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Description = Description;
            inValue.Body.Id = Id;
            RankingWebApp.ServiceReference1.CreateGameResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).CreateGame(inValue);
            return retVal.Body.CreateGameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.CreateUserResponse RankingWebApp.ServiceReference1.Service1Soap.CreateUser(RankingWebApp.ServiceReference1.CreateUserRequest request) {
            return base.Channel.CreateUser(request);
        }
        
        public bool CreateUser(string Name, string FileName) {
            RankingWebApp.ServiceReference1.CreateUserRequest inValue = new RankingWebApp.ServiceReference1.CreateUserRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.CreateUserRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.FileName = FileName;
            RankingWebApp.ServiceReference1.CreateUserResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).CreateUser(inValue);
            return retVal.Body.CreateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.CreateFaceBookUserResponse RankingWebApp.ServiceReference1.Service1Soap.CreateFaceBookUser(RankingWebApp.ServiceReference1.CreateFaceBookUserRequest request) {
            return base.Channel.CreateFaceBookUser(request);
        }
        
        public bool CreateFaceBookUser(string Name, string FileName, string FaceBook) {
            RankingWebApp.ServiceReference1.CreateFaceBookUserRequest inValue = new RankingWebApp.ServiceReference1.CreateFaceBookUserRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.CreateFaceBookUserRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.FileName = FileName;
            inValue.Body.FaceBook = FaceBook;
            RankingWebApp.ServiceReference1.CreateFaceBookUserResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).CreateFaceBookUser(inValue);
            return retVal.Body.CreateFaceBookUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.CreateRankingEntryResponse RankingWebApp.ServiceReference1.Service1Soap.CreateRankingEntry(RankingWebApp.ServiceReference1.CreateRankingEntryRequest request) {
            return base.Channel.CreateRankingEntry(request);
        }
        
        public bool CreateRankingEntry(string GameId, string Time, string UserId, int Points) {
            RankingWebApp.ServiceReference1.CreateRankingEntryRequest inValue = new RankingWebApp.ServiceReference1.CreateRankingEntryRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.CreateRankingEntryRequestBody();
            inValue.Body.GameId = GameId;
            inValue.Body.Time = Time;
            inValue.Body.UserId = UserId;
            inValue.Body.Points = Points;
            RankingWebApp.ServiceReference1.CreateRankingEntryResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).CreateRankingEntry(inValue);
            return retVal.Body.CreateRankingEntryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.GetItemResponse RankingWebApp.ServiceReference1.Service1Soap.GetItem(RankingWebApp.ServiceReference1.GetItemRequest request) {
            return base.Channel.GetItem(request);
        }
        
        public string GetItem(string list, string field, string item) {
            RankingWebApp.ServiceReference1.GetItemRequest inValue = new RankingWebApp.ServiceReference1.GetItemRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.GetItemRequestBody();
            inValue.Body.list = list;
            inValue.Body.field = field;
            inValue.Body.item = item;
            RankingWebApp.ServiceReference1.GetItemResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).GetItem(inValue);
            return retVal.Body.GetItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RankingWebApp.ServiceReference1.GetListResponse RankingWebApp.ServiceReference1.Service1Soap.GetList(RankingWebApp.ServiceReference1.GetListRequest request) {
            return base.Channel.GetList(request);
        }
        
        public RankingWebApp.ServiceReference1.ArrayOfString GetList(string item) {
            RankingWebApp.ServiceReference1.GetListRequest inValue = new RankingWebApp.ServiceReference1.GetListRequest();
            inValue.Body = new RankingWebApp.ServiceReference1.GetListRequestBody();
            inValue.Body.item = item;
            RankingWebApp.ServiceReference1.GetListResponse retVal = ((RankingWebApp.ServiceReference1.Service1Soap)(this)).GetList(inValue);
            return retVal.Body.GetListResult;
        }
    }
}
